package io.trustep.rules

import io.trustep.drools.models.Procedimento;
import io.trustep.entities.RegraOperadoraEntity;

global io.trustep.calculators.CalculadoraService calculadora;



// ─────────────────────────────────────────────────────────────────────────────
// PROCEDIMENTO (Etapa de Cálculo Baseado na Operadora - Data Driven)
// ─────────────────────────────────────────────────────────────────────────────

// Regra que cruza os dados do Procedimento com as Regras de Operadora que estão no Banco
rule "Aplicar Regra Dinamica da Operadora"
    when
        // 1. Pega um procedimento que ainda não teve o valor calculado
        $p : Procedimento(
            $op : operadora != null, 
            $cpf : cpfExecutante, 
            $tipo : tipo, 
            $dataExecucao : dataExecucao,
            $idade : idadePaciente,
            $carater : caraterAtendimento,
            $grau : grauParticipacao,
            $regrasApp : regrasAplicadas // Extrai a lista de regras aplicadas
        )
        
        // 2. O Drools busca na memória uma regra que "dê match" e que AINDA NÃO FOI APLICADA
        $regra : RegraOperadoraEntity(
            !$regrasApp.contains(descricaoLog), // Evita loop infinito e permite cascata!
            operadora.equalsIgnoreCase($op),
            (cpfExecutante == null || cpfExecutante == $cpf),
            (tipoProcedimento == null || tipoProcedimento.equalsIgnoreCase($tipo)),
            
            // CONDIÇÕES DE TEMPO E RISCO:
            (dataInicio == null || ($dataExecucao != null && dataInicio <= $dataExecucao)),
            (dataFim == null || ($dataExecucao != null && dataFim >= $dataExecucao)),
            (idadeMinima == null || ($idade != null && idadeMinima <= $idade)),
            (idadeMaxima == null || ($idade != null && idadeMaxima >= $idade)),
            (caraterAtendimento == null || caraterAtendimento == $carater),
            (grauParticipacao == null || grauParticipacao == $grau)
        )
    then
        // O Drools decidiu que essa regra se aplica! Manda o Java aplicar a matemática.
        calculadora.aplicarRegra($p, $regra);
        update($p);
end

// Regra de fallback caso nenhuma regra dê match
rule "Fallback Sem Regra Especifica"
    salience -10 // Executa por último
    when
        $p : Procedimento(valorApurado == null)
    then
        calculadora.aplicarSemRegra($p);
        update($p);
end